=== fcolombo7/ing-sw-2019-craighero-colombo-delvecchio/src/main/resources/boards/board_schema.dtd
<!ELEMENT board (row+)>
<!ELEMENT door (#PCDATA)>
<!ELEMENT doors (door,door,door,door)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT square (type,(color,doors)?)>
<!ELEMENT row (square+)>
<!ATTLIST board
        rowLength CDATA "3"
        colLength CDATA "4">
<!ATTLIST door
        direction CDATA #REQUIRED>

=== fcolombo7/ing-sw-2019-craighero-colombo-delvecchio/src/main/Resources/boards/board1.xml
<?xml version="1.0"?>
<!--Board 1: good for 3 or 4 players-->
<!DOCTYPE board SYSTEM "board_schema.dtd">
<board>
    <row>
        <square>
            <type>Ammo</type>
            <color>BLUE</color>
            <doors>
                <door direction="N">false</door>
                <door direction="E">false</door>
                <door direction="S">true</door>
                <door direction="W">false</door>
            </doors>
        </square>
        <square>
            <type>Ammo</type>
            <color>BLUE</color>
            <doors>
                <door direction="N">false</door>
                <door direction="E">false</door>
                <door direction="S">false</door>
                <door direction="W">false</door>
            </doors>
        </square>
        <square>
            <type>Weapon</type>
            <color>BLUE</color>
            <doors>
                <door direction="N">false</door>
                <door direction="E">false</door>
                <door direction="S">true</door>
                <door direction="W">false</door>
            </doors>
        </square>
        <square>
            <type>empty</type>
        </square>
    </row>
    <row>
        <square>
            <type>Weapon</type>
            <color>RED</color>
            <doors>
                <door direction="N">true</door>
                <door direction="E">false</door>
                <door direction="S">false</door>
                <door direction="W">false</door>
            </doors>
        </square>
        <square>
            <type>Ammo</type>
            <color>RED</color>
            <doors>
                <door direction="N">false</door>
                <door direction="E">false</door>
                <door direction="S">true</door>
                <door direction="W">false</door>
            </doors>
        </square>
        <square>
            <type>Ammo</type>
            <color>RED</color>
            <doors>
                <door direction="N">true</door>
                <door direction="E">true</door>
                <door direction="S">false</door>
                <door direction="W">false</door>
            </doors>
        </square>
        <square>
            <type>Ammo</type>
            <color>YELLOW</color>
            <doors>
                <door direction="N">false</door>
                <door direction="E">false</door>
                <door direction="S">false</door>
                <door direction="W">true</door>
            </doors>
        </square>
    </row>
    <row>
        <square>
            <type>Empty</type>
        </square>
        <square>
            <type>Ammo</type>
            <color>WHITE</color>
            <doors>
                <door direction="N">true</door>
                <door direction="E">false</door>
                <door direction="S">false</door>
                <door direction="W">false</door>
            </doors>
        </square>
        <square>
            <type>Ammo</type>
            <color>WHITE</color>
            <doors>
                <door direction="N">false</door>
                <door direction="E">true</door>
                <door direction="S">false</door>
                <door direction="W">false</door>
            </doors>
        </square>
        <square>
            <type>WEAPON</type>
            <color>YELLOW</color>
            <doors>
                <door direction="N">false</door>
                <door direction="E">false</door>
                <door direction="S">false</door>
                <door direction="W">true</door>
            </doors>
        </square>
    </row>
</board>
