=== fcolombo7/ing-sw-2019-craighero-colombo-delvecchio/src/main/Resources/config.dtd
<!ELEMENT config (weapons, powerups, ammos)>
<!ELEMENT weapons (weapon+)>
<!ELEMENT weapon (id,name,path)>
<!ELEMENT powerups (powerup+)>
<!ELEMENT powerup (id,name,path)>
<!ELEMENT ammos (ammo+)>
<!ELEMENT ammo (id,pow,colors)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT pow (#PCDATA)>
<!ELEMENT colors (#PCDATA)>
<!ATTLIST powerups
        quantity CDATA #REQUIRED>
<!ATTLIST weapons
        quantity CDATA #REQUIRED>

=== fcolombo7/ing-sw-2019-craighero-colombo-delvecchio/src/main/Resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config>
  <weapons quantity="">
    <weapon>
      <id>15</id>
      <name>Martello_Ionico</name>
      <path>src/main/Resources/weapons/martelloionico.xml</path>
    </weapon>
    <weapon>
      <id>16</id>
      <name>Spada_Fotonica</name>
      <path>src/main/Resources/weapons/spadafotonica.xml</path>
    </weapon>
    <weapon>
      <id>17</id>
      <name>Cyberguanto</name>
      <path>src/main/Resources/weapons/cyberguanto.xml</path>
    </weapon>
    <weapon>
      <id>18</id>
      <name>Fucile_A_Pompa</name>
      <path>src/main/Resources/weapons/fucileapompa.xml</path>
    </weapon>
    <weapon>
      <id>19</id>
      <name>Fucile_Laser</name>
      <path>src/main/Resources/weapons/fucilelaser.xml</path>
    </weapon>
    <weapon>
      <id>20</id>
      <name>Zx-2</name>
      <path>src/main/Resources/weapons/zx-2.xml</path>
    </weapon>
    <weapon>
      <id>21</id>
      <name>Onda_D'Urto</name>
      <path>src/main/Resources/weapons/ondadurto.xml</path>
    </weapon>
    <weapon>
      <id>22</id>
      <name>Cannone_Vortex</name>
      <path>src/main/Resources/weapons/cannonevortex.xml</path>
    </weapon>
    <weapon>
      <id>23</id>
      <name>Razzo_Termico</name>
      <path>src/main/Resources/weapons/razzotermico.xml</path>
    </weapon>
    <weapon>
      <id>24</id>
      <name>Lanciarazzi</name>
      <path>src/main/Resources/weapons/lanciarazzi.xml</path>
    </weapon>
    <weapon>
      <id>25</id>
      <name>Lanciagranate</name>
      <path>src/main/Resources/weapons/lanciagranate.xml</path>
    </weapon>
    <weapon>
      <id>26</id>
      <name>Lanciafiamme</name>
      <path>src/main/Resources/weapons/lanciafiamme.xml</path>
    </weapon>
    <weapon>
      <id>27</id>
      <name>Vulcanizzatore</name>
      <path>src/main/Resources/weapons/vulcanizzatore.xml</path>
    </weapon>
    <weapon>
      <id>28</id>
      <name>Raggio_Solare</name>
      <path>src/main/Resources/weapons/raggiosolare.xml</path>
    </weapon>
    <weapon>
      <id>29</id>
      <name>Torpedine</name>
      <path>src/main/Resources/weapons/torpedine.xml</path>
    </weapon>
    <weapon>
      <id>30</id>
      <name>Raggio_Traente</name>
      <path>src/main/Resources/weapons/raggiotraente.xml</path>
    </weapon>
    <weapon>
      <id>31</id>
      <name>Fucile_Di_Precisione</name>
      <path>src/main/Resources/weapons/fucilediprecisione.xml</path>
    </weapon>
    <weapon>
      <id>32</id>
      <name>Fucile_Al_Plasma</name>
      <path>src/main/Resources/weapons/fucilealplasma.xml</path>
    </weapon>
    <weapon>
      <id>33</id>
      <name>Mitragliatrice</name>
      <path>src/main/Resources/weapons/mitragliatrice.xml</path>
    </weapon>
    <weapon>
      <id>34</id>
      <name>Distruttore</name>
      <path>src/main/Resources/weapons/distruttore.xml</path>
    </weapon>
    <weapon>
      <id>35</id>
      <name>Falce_Protonica</name>
      <path>src/main/Resources/weapons/falceprotonica.xml</path>
    </weapon>
  </weapons>
  <powerups quantity="3">
    <powerup>
      <id>022</id>
      <name>Granata_Venom</name>
      <path>src/main/Resources/powerups/granatavenomb.xml</path>
    </powerup>
    <powerup>
      <id>023</id>
      <name>Granata_Venom</name>
      <path>src/main/Resources/powerups/granatavenomr.xml</path>
    </powerup>
    <powerup>
      <id>024</id>
      <name>Granata_Venom</name>
      <path>src/main/Resources/powerups/granatavenomy.xml</path>
    </powerup>
    <powerup>
      <id>025</id>
      <name>Mirino</name>
      <path>src/main/Resources/powerups/mirinob.xml</path>
    </powerup>
    <powerup>
      <id>026</id>
      <name>Mirino</name>
      <path>src/main/Resources/powerups/mirinor.xml</path>
    </powerup>
    <powerup>
      <id>027</id>
      <name>Mirino</name>
      <path>src/main/Resources/powerups/mirinoy.xml</path>
    </powerup>
    <powerup>
      <id>028</id>
      <name>Raggio_Cinetico</name>
      <path>src/main/Resources/powerups/raggiocineticob.xml</path>
    </powerup>
    <powerup>
      <id>029</id>
      <name>Raggio_Cinetico</name>
      <path>src/main/Resources/powerups/raggiocineticor.xml</path>
    </powerup>
    <powerup>
      <id>0210</id>
      <name>Raggio_Cinetico</name>
      <path>src/main/Resources/powerups/raggiocineticoy.xml</path>
    </powerup>
    <powerup>
      <id>0211</id>
      <name>Teletrasporto</name>
      <path>src/main/Resources/powerups/teletrasportob.xml</path>
    </powerup>
    <powerup>
      <id>0212</id>
      <name>Teletrasporto</name>
      <path>src/main/Resources/powerups/teletrasportor.xml</path>
    </powerup>
    <powerup>
      <id>0213</id>
      <name>Teletrasporto</name>
      <path>src/main/Resources/powerups/teletrasportoy.xml</path>
    </powerup>
  </powerups>
  <ammos>
    <ammo>
      <id>042</id>
      <pow>false</pow>
      <colors>ybb</colors>
    </ammo>
    <ammo>
      <id>043</id>
      <pow>false</pow>
      <colors>yrr</colors>
    </ammo>
    <ammo>
      <id>044</id>
      <pow>false</pow>
      <colors>rbb</colors>
    </ammo>
    <ammo>
      <id>045</id>
      <pow>false</pow>
      <colors>ryy</colors>
    </ammo>
    <ammo>
      <id>046</id>
      <pow>false</pow>
      <colors>byy</colors>
    </ammo>
    <ammo>
      <id>047</id>
      <pow>false</pow>
      <colors>brr</colors>
    </ammo>
    <ammo>
      <id>048</id>
      <pow>false</pow>
      <colors>ybb</colors>
    </ammo>
    <ammo>
      <id>049</id>
      <pow>false</pow>
      <colors>yrr</colors>
    </ammo>
    <ammo>
      <id>0410</id>
      <pow>false</pow>
      <colors>rbb</colors>
    </ammo>
    <ammo>
      <id>0411</id>
      <pow>false</pow>
      <colors>ryy</colors>
    </ammo>
    <ammo>
      <id>0412</id>
      <pow>false</pow>
      <colors>byy</colors>
    </ammo>
    <ammo>
      <id>0413</id>
      <pow>false</pow>
      <colors>brr</colors>
    </ammo>
    <ammo>
      <id>0414</id>
      <pow>false</pow>
      <colors>ybb</colors>
    </ammo>
    <ammo>
      <id>0415</id>
      <pow>false</pow>
      <colors>yrr</colors>
    </ammo>
    <ammo>
      <id>0416</id>
      <pow>false</pow>
      <colors>rbb</colors>
    </ammo>
    <ammo>
      <id>0417</id>
      <pow>false</pow>
      <colors>ryy</colors>
    </ammo>
    <ammo>
      <id>0418</id>
      <pow>false</pow>
      <colors>byy</colors>
    </ammo>
    <ammo>
      <id>0419</id>
      <pow>false</pow>
      <colors>brr</colors>
    </ammo>
    <ammo>
      <id>0420</id>
      <pow>true</pow>
      <colors>yy</colors>
    </ammo>
    <ammo>
      <id>0421</id>
      <pow>true</pow>
      <colors>rr</colors>
    </ammo>
    <ammo>
      <id>0422</id>
      <pow>true</pow>
      <colors>bb</colors>
    </ammo>
    <ammo>
      <id>0423</id>
      <pow>true</pow>
      <colors>yr</colors>
    </ammo>
    <ammo>
      <id>0424</id>
      <pow>true</pow>
      <colors>yb</colors>
    </ammo>
    <ammo>
      <id>0425</id>
      <pow>true</pow>
      <colors>rb</colors>
    </ammo>
    <ammo>
      <id>0426</id>
      <pow>true</pow>
      <colors>yr</colors>
    </ammo>
    <ammo>
      <id>0427</id>
      <pow>true</pow>
      <colors>yb</colors>
    </ammo>
    <ammo>
      <id>0428</id>
      <pow>true</pow>
      <colors>rb</colors>
    </ammo>
    <ammo>
      <id>0429</id>
      <pow>true</pow>
      <colors>yy</colors>
    </ammo>
    <ammo>
      <id>0430</id>
      <pow>true</pow>
      <colors>rr</colors>
    </ammo>
    <ammo>
      <id>0431</id>
      <pow>true</pow>
      <colors>bb</colors>
    </ammo>
    <ammo>
      <id>0432</id>
      <pow>true</pow>
      <colors>yr</colors>
    </ammo>
    <ammo>
      <id>0433</id>
      <pow>true</pow>
      <colors>yb</colors>
    </ammo>
    <ammo>
      <id>0434</id>
      <pow>true</pow>
      <colors>rb</colors>
    </ammo>
    <ammo>
      <id>0435</id>
      <pow>true</pow>
      <colors>yr</colors>
    </ammo>
    <ammo>
      <id>0436</id>
      <pow>true</pow>
      <colors>yb</colors>
    </ammo>
    <ammo>
      <id>0437</id>
      <pow>true</pow>
      <colors>rb</colors>
    </ammo>
  </ammos>
  <skull>8</skull>
</config>

=== fcolombo7/ing-sw-2019-craighero-colombo-delvecchio/src/test/Resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config>
  <weapons quantity="">
    <weapon>
      <id>022</id>
      <name>Martello_Ionico</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>023</id>
      <name>Spada_Fotonica</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>024</id>
      <name>Cyberguanto</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>025</id>
      <name>Fucile_A_Pompa</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>026</id>
      <name>Fucile_Laser</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>027</id>
      <name>Zx-2</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>028</id>
      <name>Onda_D'Urto</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>029</id>
      <name>Cannone_Vortex</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0210</id>
      <name>Razzo_Termico</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0211</id>
      <name>Lanciarazzi</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0212</id>
      <name>Lanciagranate</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0213</id>
      <name>Lanciafiamme</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0214</id>
      <name>Vulcanizzatore</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0215</id>
      <name>Raggio_Solare</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0216</id>
      <name>Torpedine</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0217</id>
      <name>Raggio_Traente</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0218</id>
      <name>Fucile_Di_Precisione</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0219</id>
      <name>Fucile_Al_Plasma</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0220</id>
      <name>Mitragliatrice</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0221</id>
      <name>Distruttore</name>
      <path>-</path>
    </weapon>
    <weapon>
      <id>0222</id>
      <name>Falce_Protonica</name>
      <path>-</path>
    </weapon>
  </weapons>
  <powerups quantity="3">
    <powerup>
      <id>022</id>
      <name>Granata_Venom</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>023</id>
      <name>Granata_Venom</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>024</id>
      <name>Granata_Venom</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>025</id>
      <name>Mirino</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>026</id>
      <name>Mirino</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>027</id>
      <name>Mirino</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>028</id>
      <name>Raggio_Cinetico</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>029</id>
      <name>Raggio_Cinetico</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>0210</id>
      <name>Raggio_Cinetico</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>0211</id>
      <name>Teletrasporto</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>0212</id>
      <name>Teletrasporto</name>
      <path>-</path>
    </powerup>
    <powerup>
      <id>0213</id>
      <name>Teletrasporto</name>
      <path>-</path>
    </powerup>
  </powerups>
  <ammos>
    <ammo>
      <id>042</id>
      <pow>false</pow>
      <colors>ybb</colors>
    </ammo>
    <ammo>
      <id>043</id>
      <pow>false</pow>
      <colors>yrr</colors>
    </ammo>
    <ammo>
      <id>044</id>
      <pow>false</pow>
      <colors>rbb</colors>
    </ammo>
    <ammo>
      <id>045</id>
      <pow>false</pow>
      <colors>ryy</colors>
    </ammo>
    <ammo>
      <id>046</id>
      <pow>false</pow>
      <colors>byy</colors>
    </ammo>
    <ammo>
      <id>047</id>
      <pow>false</pow>
      <colors>brr</colors>
    </ammo>
    <ammo>
      <id>048</id>
      <pow>false</pow>
      <colors>ybb</colors>
    </ammo>
    <ammo>
      <id>049</id>
      <pow>false</pow>
      <colors>yrr</colors>
    </ammo>
    <ammo>
      <id>0410</id>
      <pow>false</pow>
      <colors>rbb</colors>
    </ammo>
    <ammo>
      <id>0411</id>
      <pow>false</pow>
      <colors>ryy</colors>
    </ammo>
    <ammo>
      <id>0412</id>
      <pow>false</pow>
      <colors>byy</colors>
    </ammo>
    <ammo>
      <id>0413</id>
      <pow>false</pow>
      <colors>brr</colors>
    </ammo>
    <ammo>
      <id>0414</id>
      <pow>false</pow>
      <colors>ybb</colors>
    </ammo>
    <ammo>
      <id>0415</id>
      <pow>false</pow>
      <colors>yrr</colors>
    </ammo>
    <ammo>
      <id>0416</id>
      <pow>false</pow>
      <colors>rbb</colors>
    </ammo>
    <ammo>
      <id>0417</id>
      <pow>false</pow>
      <colors>ryy</colors>
    </ammo>
    <ammo>
      <id>0418</id>
      <pow>false</pow>
      <colors>byy</colors>
    </ammo>
    <ammo>
      <id>0419</id>
      <pow>false</pow>
      <colors>brr</colors>
    </ammo>
    <ammo>
      <id>0420</id>
      <pow>true</pow>
      <colors>yy</colors>
    </ammo>
    <ammo>
      <id>0421</id>
      <pow>true</pow>
      <colors>rr</colors>
    </ammo>
    <ammo>
      <id>0422</id>
      <pow>true</pow>
      <colors>bb</colors>
    </ammo>
    <ammo>
      <id>0423</id>
      <pow>true</pow>
      <colors>yr</colors>
    </ammo>
    <ammo>
      <id>0424</id>
      <pow>true</pow>
      <colors>yb</colors>
    </ammo>
    <ammo>
      <id>0425</id>
      <pow>true</pow>
      <colors>rb</colors>
    </ammo>
    <ammo>
      <id>0426</id>
      <pow>true</pow>
      <colors>yr</colors>
    </ammo>
    <ammo>
      <id>0427</id>
      <pow>true</pow>
      <colors>yb</colors>
    </ammo>
    <ammo>
      <id>0428</id>
      <pow>true</pow>
      <colors>rb</colors>
    </ammo>
    <ammo>
      <id>0429</id>
      <pow>true</pow>
      <colors>yy</colors>
    </ammo>
    <ammo>
      <id>0430</id>
      <pow>true</pow>
      <colors>rr</colors>
    </ammo>
    <ammo>
      <id>0431</id>
      <pow>true</pow>
      <colors>bb</colors>
    </ammo>
    <ammo>
      <id>0432</id>
      <pow>true</pow>
      <colors>yr</colors>
    </ammo>
    <ammo>
      <id>0433</id>
      <pow>true</pow>
      <colors>yb</colors>
    </ammo>
    <ammo>
      <id>0434</id>
      <pow>true</pow>
      <colors>rb</colors>
    </ammo>
    <ammo>
      <id>0435</id>
      <pow>true</pow>
      <colors>yr</colors>
    </ammo>
    <ammo>
      <id>0436</id>
      <pow>true</pow>
      <colors>yb</colors>
    </ammo>
    <ammo>
      <id>0437</id>
      <pow>true</pow>
      <colors>rb</colors>
    </ammo>
  </ammos>
</config>
